### ISSUE TITLE
`rose_web_bg.wasm` not found and wasm compilation error on start

### ISSUE THREAD

**Issue by wodeni** [rose-lang/rose#120]
Continuing #119, I did manage to work around the TLA issue by adding `vite-plugin-top-level-await` but immediately ran into another issue where the page doesn't render and the console shows the following:

```
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:5174/node_modules/.vite/deps/rose_web_bg.wasm

rose_web.js:1526 `WebAssembly.instantiateStreaming` failed because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:
 TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok

Uncaught CompileError: WebAssembly.instantiate(): BufferSource argument is empty
    at __wbg_load (rose_web.js:1535:34)
    at async __wbg_init (rose_web.js:1806:34)
    at async browser.js:3:1
```

**Comment by wodeni** [comment]
My current workaround is to add this to my `vite.config.ts`:
```diff
export default defineConfig({
  plugins: [solid(), topLevelAwait()],
+  optimizeDeps: { exclude: ["rose"] },
});

```

**Comment by samestep** [comment]
I documented the workaround in 3ae4bc106ca6306a4f0ecb8c63f4ff82e945ab7f.
